.TH "zzip_compr_str" "3" "0\&.13\&.69" "zziplib" "zziplib Function List"
.ie \n(.g .ds Aq \(aq
.el        .ds Aq 
.nh
.ad l
.SH "NAME"
zzip_compr_str \-  compr name\&. 
.SH "SYNOPSIS"
.sp
.nf
.B "#include <zzip/lib\&.h>"
.B ""
.sp
zzip_char_t *
\fIzzip_compr_str\fR(int compr)


.fi
.sp
.SH "DESCRIPTION"
 The \fIzzip_compr_str\fP function returns the static const string of the known compression methods, Unknown id values will return just "zipped" as the string code.  
.sp
.sp
.SH "AUTHOR"
 Guido Draheim <guidod@gmx.de> 
.sp
.sp
.SH "COPYRIGHT"
 Copyright (c) Guido Draheim, use under copyleft (LGPL,MPL)  
.sp
.sp
