.TH "zzip_filesize" "3" "0\&.13\&.69" "zziplib" "zziplib Function List"
.ie \n(.g .ds Aq \(aq
.el        .ds Aq 
.nh
.ad l
.SH "NAME"
zzip_filesize \-  get file size\&. 
.SH "SYNOPSIS"
.sp
.nf
.B "#include <zzip/lib\&.h>"
.B ""
.sp
zzip_off_t
\fIzzip_filesize\fR(int fd)


.fi
.sp
.SH "DESCRIPTION"
 The \fIzzip_filesize\fP function works on a real file descriptor.  
.sp
.sp
.SH "AUTHOR"
 	Guido Draheim <guidod@gmx.de> Mike Nordell <tamlin-@-algonet-se> 
.sp
.sp
.SH "COPYRIGHT"
 Copyright (c) Guido Draheim, use under copyleft (LGPL,MPL)  
.sp
.sp
